[package]
name = "bee_code"
version = "0.3.0"
edition = "2021"
description = "A library for encoding and decoding bencode formatted data"
license = "MIT"
repository = "https://github.com/mtodorov95/bee_code"
categories = ["encoding"]
keywords = ["bencode", "bittorrent"]
